/*
http://rosalind.info/problems/dna/
*/

var str ="ACGTTCTGATGTCGGACTGCTGACTAAAATGATTCTGGCACGTGGAACGTGCAGTTGCGTTGGGCACCTTGTAACCCACAATTAACGGATTCCATATAGCGTAAGAAAACTCCAGTTACTAGCCCTTAAGATCTATTCGACACGACGTGGTAAATCCCAGTTATCGCGATAAGTCCGGGCGCTCCCCGTCTATGCACAGAAATTATTGCCGGCTACTTTTGTTATACCCCAATGTACGGATAGCCGGCAAGTTTACGTATACACGCTCAATGTCATATTAGCCATAACGAGTACGTATAGAGCCGCTTCCCGTTTTATGTGATTGTGCAACGGGACAAAACTAAGATGTCTCGATCAGTGTAGCTTAAGTCGTCTTCCGGGGGAGAACTGCTGGCGATCGTTGAGACGTCGGAAGCGGGTAATACAAAAATCCAGAGGGACTATCTAATAAAGATGGAGACGGCAGAGAACGAAGTCAACGTCTGGGGGGCGAAAAGACACGTGGGTGCTCCCTAACCACGCCTGTGTGACGTCAGGCAGTCTAAATAATCAACAGATAGTAATTCTTACGTCTAGCAGAACACGCCGCAGACACGTAGTAGAGCGACCCGCGCCTAATCTTAATACCAGGCGTTGTCTTCTGGGCCTTGTCGCCGAAATTATTAAATACACCTCCTATCATGGGGTAGGCAGGAGATACTACGCGGACCCCCAGGGGGGTCTGTTCACTTCTATGTCACCACAACATTGACCCTCCGCCTAGAATTCTCATTAATTGGGCGTCGCGAAACAACAGACTTATCGAACGGGCTCGGCAGACGTAAATTATATGAGAAAAGAAGCGGGATTTTATACTTTCGGTGGTCACGCGTGTGTTTGATGCCACGCTCACCGCGCGTCCTCCTTTACTGCTACACAGCACAAGCTCGACGTGGCCTGTTCGAAGAGGCGGTGTA";
var tabG=[];
var tabT=[];
var tabA=[];
var tabC=[];

for (var i=0; i<str.length; i++){
    if (str.charAt(i)==="A"){tabA.push(str.charAt(i))

    }
    else if (str.charAt(i)==="C"){tabC.push(str.charAt(i))

    }
    else if (str.charAt(i)==="G"){tabG.push(str.charAt(i))

    }
    else {tabT.push(str.charAt(i))

    }
}
console.log(tabG.length,tabT.length, tabA.length, tabC.length);

