
//  http://rosalind.info/problems/subs/
const dna1="GATATATGCATATACTT"
const dna2="ATAT"
 for (let i=0; i<dna1.length - dna2.length; i++){

   if (dna1.charAt(i)==="A"){
    if (dna1.charAt(i+1)==="T"){
            if(dna1.charAt(i+2)==="A"){
                if(dna1.charAt(i+3)==="T"){
console.log(i);
console.log(dna1.charAt(i));
                }
            }
        }
    }
}


function ttt() {

for (let j=0; j<dna1.length; j++){
   if ((dna1.charAt(j)==="A")&&(dna1.charAt(j+1)==="T")&&(dna1.charAt(j+2)==="A")&&(dna1.charAt(j+3)==="T")){
console.log(dna1.indexOf(dna2));
   }
}

}
ttt();


function subs(rna,rna2){
    let result = [];

    for (let i = 0; i < rna.length; ++i){

        if(rna.substr(i,rna2.length)==rna2){
            result.push(i+1);

        }
    }return result.join(' ')
}
let result=subs("GGATCTTTGGATCTTTATTGCGGATCTTTTCCGATCTTTAAGATCTTTGAAGATCTTTGATCTTTGAGATCTTTATCGATCTTTTTGATCTTTGATCTTTAGGATCTTTCCATTAGATCTTTTTGATCTTTCGAGATCTTTAGATCTTTGGATCTTTGTAGATCTTTTGATCTTTAGTCAGACTAAGATCTTTGGGATCTTTAAGGATCTTTACTCCCCCGATCTTTGCGAGATCTTTATCCGATCTTTCAGATCTTTGATCTTTAGGGATCTTTACGATCATTGATCTTTCACGGATCTTTAGATCTTTTGCCGTTGATCTTTGATCTTTGATCTTTGGATCTTTGATCTTTGATCTTTGATCTTTTTCTTTGATCTTTATGCCGATCTTTGATCTTTGATCTTTGATCTTTGATCTTTGATCTTTTGATCTTTGATCTTTCGATCTTTGATCTTTGGGGGATCTTTGATCTTTGATCTTTGATCTTTAATGATCTTTTGTTGTGATCTTTGATCTTTTGATCTTTTATACTGGGAGATCTTTAGATCTTTGATCTTTGAAGATCTTTGATCTTTACGATCTTTTAGATCTTTATGATCTTTGATCTTTTTATTGCGAATGGATCTTTAATGATCTTTGAGATCTTTGCACTGATCTTTGGATCTTTTGATCTTTATCAACGATCTTTGCGATCTTTACATGCCGGTCGGATCTTTGGATCTTTTGGTAGATCTTTAGATCTTTGATCTTTTGATCTTTCTCGATCTTTCGATCTTTCTCAGCGATCTTTGATCTTTGAACGATCTTTGATCTTTAGATCTTTGATCTTTGGATCTTTTTGCGGATCTTTCCACGATCTTTAGGAGATCTTTGGATCTTTCGATCTTTGATCTTTTCCGTGATCTTTGATCTTTGATCTTTGGGATCTTTGGTGATCTTTCTCGATCTTTTGATCTTTGCCC","GATCTTTGA");
console.log(result);


